name: Beta release on Develop

on:
  release:
    types: [ prereleased ]
      
jobs:
  prerelease:
    name: Beta release
    runs-on: ubuntu-latest
    if: ${{ github.event.release.target_commitish == 'develop' }}

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name $GITHUB_ACTOR
          git config --global user.email $GITHUB_ACTOR@users.noreply.github.com
        
      - name: Setup Node ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
            ./.yarn
          key: ${{ runner.os }}-yarn-modules-${{ hashFiles('./yarn.lock') }}

      - name: Install build dependencies
        run: |
          yarn --prefer-offline --pure-lockfile --cache-folder .yarn --modules-folder node_modules

      - name: Build
        run: |
          export BASE_URL=$PUBLIC_URL
          yarn build
        env:
          SKIP_PREFLIGHT_CHECK: true
          PUBLIC_URL: https://beta.discuzz.mph.am/
          SERVICE_CONFIG: ${{ secrets.SERVICE_CONFIG }}
          AUTHS: ${{ secrets.AUTHS }}

      - name: Set version
        run: |
          yarn version:set prepatch --no-git-tag-version --preid beta-$GITHUB_SHA && yarn version:commit

      - name: Publish to NPM
        run: |
          yarn version:release --dist-tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}